### ISSUE TITLE
Allow configuring umask permissions

### ISSUE THREAD

**Issue by zsorizs** [home-operations/containers#440]
For a long time I was using an earlier version of the qbittorrent container by onedr0p. UMASK set in env was applied and the completed files got the permissions I wanted.

Upgrading from 4.5.4 to 4.6.7 and then 5.1.0 broke this.

Not sure how was this handled earlier, but adding this should be enough:
```
if [ -n "$UMASK" ]; then
  echo "Setting umask to $UMASK"
  umask "$UMASK"
fi
```

**Comment by onedr0p** [comment]
Umask was removed awhile ago from the container entrypoints, the PR https://github.com/home-operations/containers/pull/408 just cleaned up old references to it. 

With that said what is your use case for changing the umask, meaning why do you need to adjust the default umask permissions (0022) of files created?

I am not completely opposed to adding it back but I would like to know more about what problem it solves for you.

Keep in mind the most common ones:

- `0002` is `0664` for files and `0775` for folders
- `0022` is `0644` for files and `0755` for folders (default)

**Comment by onedr0p** [comment]
I am going to go ahead and close this since there hasn't been any follow up from OP in the past two weeks.

For anyone visiting here: A workaround could be to create a script for qb to change the permissions of downloaded files and have it execute on completion of a torrent.

**Comment by zsorizs** [comment]
Sorry for not responding earlier.

With umask 0022 (the default in Alpine), you don't get write permissions for anybody except the user used by the qbittorrent.

With umask 0002, I get write rights for other users that are in the same group.

In my preferred setup the completed files are hard linked to the target directory by a different user. Hard linking requires write permission for the source file. I don't want to copy because that would be too costly. I don't want to move either because the torrent is still seeded.

The solution for me was to add this to the release file:
```
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.0
            command: ["/bin/sh", "-c"]
            args:
              - |
                # Set the desired umask
                umask 002
                exec /usr/bin/catatonit -- /entrypoint.sh "$@"
```

Setting the UMASK environment variable was nicer and did not require knowledge of the docker internals (the way the entry script should be invoked).

Since I have this solved I don't really need the UMASK variable anymore. I've opened the issue just to let you know that a feature was lost.
